### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by bigbrozer** [nVentiveUX/docker-valheim#1]
Hello sir !

If you need help on that one, let's write here the things to do before releasing **v1.0.0** to the public :smiley: 

## Todos

- [x] Write Dockerfile.
- [x] Write github action workflow to publish docker image.
- [x] Use `/usr/local` instead of `/usr` for installing maintenance files and so on to not interfere with the os installed files.
- [ ] Maybe that would be good to have a data disk for storing the docker volumes ?

**Comment by link-webcreations** [comment]
most is done, server is running fine.
